name: Build EXE

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or any version you prefer

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile guess_number.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: guess-number-exe
        path: dist/guess_number.exe
